version: "3.8"

networks:
  dataline:
    driver: bridge

volumes:
  dataline_dev:

services:
  backend:
    build:
      context: .
      target: base
    ports:
      - "0.0.0.0:7377:7377"
    environment:
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS:-http://10.10.10.168:7377,http://10.10.10.168:5173}"
      AUTH_USERNAME: "${AUTH_USERNAME}"
      AUTH_PASSWORD: "${AUTH_PASSWORD}"
    working_dir: /home/dataline/backend
    command: ["bash", "-c", "python -m alembic upgrade head && python -m uvicorn dataline.main:app --port=7377 --host=0.0.0.0 --reload"]
    volumes:
      - dataline_dev:/home/.dataline # persist local sqlite db
      - ./backend/dataline:/home/dataline/backend/dataline
      - ./backend/alembic:/home/dataline/backend/alembic
    networks:
      - dataline

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - dataline
    environment:
      VITE_API_URL: "http://10.10.10.168:7377"
